web:
    resource: "@WebBundle/Controller/"
    type:     annotation
    prefix:   /

ardid:
    resource: "@ArdidBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
