<?php

namespace ArdidBundle\Repository;

/**
 * IdentificacionTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdentificacionTipoRepository extends \Doctrine\ORM\EntityRepository
{
}
