<?php

namespace ArdidBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgramacionRepository extends EntityRepository
{
    public function devengadoPromedio($codigoEmpleado) {
        $em = $this->getEntityManager();
        $dql   = "SELECT p.vrDevengado FROM ArdidBundle:Pago p "
                . "WHERE p.codigoEmpleadoFk = " . $codigoEmpleado . "ORDER BY p.fechaDesde DESC";
        $query = $em->createQuery($dql)->setMaxResults(2);                
        $devengado = 0;
        $arResultados = $query->getResult();
        foreach ($arResultados as $arResultado) {
            $devengado += $arResultado['vrDevengado'];
        }
        return $devengado;
    }    
}