<?php

namespace ArdidBundle\Repository;

/**
 * QuejasReclamosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuejasReclamosRepository extends \Doctrine\ORM\EntityRepository
{
}
