<?php

namespace ArdidBundle\Repository;

/**
 * ReclamoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReclamoRepository extends \Doctrine\ORM\EntityRepository
{
}
