<?php

namespace ArdidBundle\Repository;

/**
 * ReclamoTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReclamoTipoRepository extends \Doctrine\ORM\EntityRepository
{
}
